#===========
#This is a testing pod for my cluster 
#===============

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-client
  namespace: prod
  labels:
    app.kubernetes.io/name: mysql-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql-client
    spec:
      containers:
        - name: mysql-client
          image: mysql:8.0
          command: ["sleep", "infinity"]  # keep pod alive for exec 
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          